export const positions = {
  president: 1,
  "vice-president": 2,
  manager: 3,
  secretary: 4,
};
export const list = [
  {
    title: "General Orientation",
    description: "the quick brown fox",
    slug: "general-orientation",
  },
  {
    title: "Special Orientation",
    description: "jumps over the lazy dog",
    slug: "speacial-orientation",
  },
  {
    title: "Intramurals",
    description: "Intramural meet",
    slug: "intramurals",
  },
  {
    title: "Trojan Olympiad",
    description: "series of competitions conducted by the organziation",
    slug: "trojan-olympiad",
  },
  {
    title: "IT Olympiad",
    description: "series of competitions conducted outside the University",
    slug: "it-olympiad",
  },
  {
    title: "Hack4Gov",
    description: "hackathon conducted by DICT",
    slug: "hack-4-gov",
  },
  {
    title: "Team Building",
    description: "Team building",
    slug: "team-building",
  },
];
export const adviser = {
  first_name: "Sheila Marie",
  last_name: "Villarin",
  position: "Professor",
  term: "2023-2024",
};
export const officers = [
  {
    first_name: "Denrei Keith",
    last_name: "De Jesus",
    position: "President",
    program: "BSCS",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Owe",
    last_name: "Altheae",
    position: "Vice-President",
    program: "BSCS",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Stephanie",
    last_name: "Palero",
    position: "Secretary",
    program: "BSCS",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Phoebe Kaye",
    last_name: "Lerog",
    position: "Treasurer",
    program: "BSIT",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Reagan James",
    last_name: "Mabawad",
    position: "Auditor",
    program: "BSCS",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Christine Gamutan",
    last_name: "Dacles",
    position: "Business Manager",
    program: "BSIT",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Jhonna Mae",
    last_name: "Awayan",
    position: "PIO",
    program: "BSIT",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Wilbert John",
    last_name: "Alfornon",
    position: "4th Year Representative",
    program: "BSCS",
    year_level: "4th",
    term: "2023-2024",
  },
  {
    first_name: "Rexdan",
    last_name: "Tautho",
    position: "3rd Year Representative",
    program: "BSIT",
    year_level: "3rd",
    term: "2023-2024",
  },
  {
    first_name: "Ariel July",
    last_name: "Traje",
    position: "2nd Year Representative",
    program: "BSIT",
    year_level: "2nd",
    term: "2023-2024",
  },
  {
    first_name: "Lord Anthony",
    last_name: "Acuna",
    position: "1st Year Representative",
    program: "BSIT",
    year_level: "2nd",
    term: "2023-2024",
  },
];

export const committees = [
  {
    first_name: "Jude Rafael",
    last_name: "Alayacyac",
    position: "Creatives Head",
    program: "BSIT",
    year_level: "2nd",
    term: "2023-2024",
  },
  {
    first_name: "Paul Tristan",
    last_name: "Dujali",
    position: "Documentations Head",
    program: "BSCS",
    year_level: "2nd",
    term: "2023-2024",
  },
  {
    first_name: "Krizmelh",
    last_name: "Bacus",
    position: "Logistics Head",
    program: "BSCS",
    year_level: "3rd",
    term: "2023-2024",
  },
];
